### ISSUE TITLE
error opening a file in linux

### ISSUE THREAD

**Issue by jeffrey0606** [cedx/open.dart#1]
This is the error catch:
Unsupported operation: Isolate.resolvePackageUri;

**Comment by jeffrey0606** [comment]
still new on GitHub. 
but i have got a workaround on this stackoverflow post ( https://stackoverflow.com/a/59411310/12879950 ).

replaced this
 `final packageUri =  await Isolate.resolvePackageUri(Uri.parse('package:open/'));`
with this
`final packageUri =  (await getProjectFile('package:open/')).uri;`

**Comment by cedx** [comment]
What is your Dart version? Is it a Flutter project?
Can you paste a snippet of your code consuming this library?

**Comment by jeffrey0606** [comment]
Dart SDK version: 2.10.4
Yes it's a flutter desktop project
`import 'package:open/open.dart';`
`try {
            await open(info["savePath"], wait: true);
          } catch (e) {
            print(e);
          }`

**Comment by cedx** [comment]
OK, everything is explained 😄 

`Isolate.resolvePackageUri` is still not supported on Flutter:
flutter/flutter#14815

You encountered this error because the library tries to use its own `xdg-open` script (as not all Linux distributions use the latest version).
See: https://github.com/cedx/open.dart/blob/v1.4.0/lib/src/io/open.dart#L32

So, a solution could be to avoid the bundled `xdg-open` script, and use the system script instead.
The mentioned `getProjectFile()` function relies on the current working directory: this is clearly not the way to go.

Could you try to remove the bundled `xdg-open` script from the library to see if it fixes this issue?

**Comment by jeffrey0606** [comment]
thanks @cedx ,  so this `getProjectFile()` could cause me problem in production?

This works:
`final process = await Process.start("xdg-open", commandArgs, mode: mode);`

but i had to copy your plugin code in my app code to try it.
please is it the right way to do it?
